In [1]:
import numpy as np
import pickle
import yaml

dir = '../models/second_order/Tc2GP_model.sav'

with open(dir, 'rb') as f:
  pkl = pickle.load(f)

print(pkl.X_train_)

[[2 2 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 ...
 [2 4 0 ... 0 0 0]
 [2 4 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


C:\Users\Bryan\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:324: UserWarning: Trying to unpickle estimator GaussianProcessRegressor from version 1.0 when using version 1.0.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [2]:
import yaml

with open('case.yml', 'r') as f:
  cases = yaml.safe_load(f)
  print(cases)

import stable_baselines3

{'mbt': {'building_blocks': [1, 2, 3, 4, 15, 22, 29, 42, 123], 'constraints': {'NUM_GROUPS': {'min': 3, 'max': 8}, 'NUM_REPEAT_GROUPS': {'min': 0, 'max': 7}, 'NUM_FUNC_GROUPS': {'min': 1, 'max': 6}, 'MOLECULAR_WEIGHT': {'min': 80, 'max': 200}, 'FLASH POINT': {'min': 273, 'max': 393}, 'MELTING_POINT': {'min': 173, 'max': 310}, 'BOILING_POINT': {'min': 373, 'max': 600}, 'LC50': {'min': 0, 'max': 4.8}, 'HSP': {'min': 18, 'max': 21}}, 'num_rings': 'all', 'level': 1}, 'surfactant': {'building_blocks': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 21, 22], 'objective': ['min', 'LC_50'], 'constraints': {'NUM_GROUPS': {'min': 20, 'max': 30}, 'NUM_REPEAT_GROUPS': {'min': 0, 'max': 15}, 'NUM_FUNC_GROUPS': {'min': 6, 'max': 10}, 'MOLECULAR_WEIGHT': {'min': 300}, 'MELTING_POINT': {'min': 300}, 'BOILING_POINT': {'min': 400}, 'LC50': {'min': 0, 'max': 4}}, 'num_rings': 'all', 'level': 1}, 'DCM': {'building_blocks': [1, 2, 3, 4, 29, 33, 34, 38, 40, 41, 44, 48, 49, 50, 51], 'objective': ['min', 'LC_50'], 'c

In [3]:

import stable_baselines3